apiVersion: apps/v1
kind: Deployment
metadata:
  name: wills-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wills-app
  template:
    metadata:
      labels:
        app: wills-app
    spec:
      containers:
      - name: wills-app
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: MESSAGE
          value: Hello from app2 APP TWO!
---
apiVersion: v1
kind: Service
metadata:
  name: wills-app
  labels:
    app: wills-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: wills-app